-- =============================================================================
-- 003_referrals.sql
-- Purpose: Referral tracking — records who referred whom and conversion status.
--
-- Frontend dependencies:
--   - referralService.js  (createReferralCode → insertReferral,
--                          trackConversion → getReferralByCode)
--   - queries.js          (insertReferral, getReferralByCode, getReferralsForUser)
--   - useAdminReferrals.js (full list, leaderboard, conversion_status filter)
--   - useAdminMetrics.js  (COUNT total + COUNT converted)
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.referral_tracking (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- The subscriber who owns the referral code
    referrer_id         UUID NOT NULL REFERENCES public.subscribers(id) ON DELETE CASCADE,

    -- The generated unique code (e.g. UNI-AB12CD)
    referral_code       TEXT NOT NULL,

    -- Email of the person who used this code (NULL until used)
    referred_email      TEXT,

    -- useAdminReferrals.js checks: conversion_status = 'converted'
    conversion_status   TEXT DEFAULT 'pending',   -- 'pending' | 'converted' | 'invalid'

    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    converted_at        TIMESTAMP WITH TIME ZONE,

    CONSTRAINT referral_code_unique UNIQUE (referral_code),
    CONSTRAINT referral_conversion_status_check CHECK (
        conversion_status IN ('pending', 'converted', 'invalid')
    )
);

COMMENT ON TABLE public.referral_tracking IS
    'Maps referral codes to referrers. One row per issued code; updated when code is used.';
COMMENT ON COLUMN public.referral_tracking.referral_code IS
    'Unique human-readable code, e.g. UNI-AB12CD. Generated by referralService.js.';
COMMENT ON COLUMN public.referral_tracking.conversion_status IS
    'Set to converted when a new subscriber joins using this code.';
